# ==================================================
# CẤU HÌNH KẾT NỐI SUPABASE - JDBC
# QUAN TRỌNG: Không chia sẻ file này lên GitHub!
# ==================================================

# Thông tin lấy từ: Supabase → Settings → Database
db.host=db.eqwtekhtwrgfabtnggyw.supabase.co
db.port=5432
db.name=postgres
db.user=postgres
db.password=Baovetaikhoan24!

# URL đầy đủ khi ghép lại:
# jdbc:postgresql://db.eqwtekhtwrgfabtnggyw.supabase.co:5432/postgres

# ==================================================
# CẤU HÌNH CLOUDFLARE R2 OBJECT STORAGE (KHO ẢNH/MEDIA)
# ==================================================
r2.endpoint=https://dd7aabd53f529f84023f58d25bdc3545.r2.cloudflarestorage.com
r2.bucket=giapha
r2.access_key=75ce4b5b09ffd36bd93280f17d748315
r2.secret_key=998b09b07f8933eb4b469375a49107f559465ba2001101ee10ed026d91a1749f
r2.public_url=https://pub-7a40043ee2ed4d8e8e87e5c0d54c65d5.r2.dev
